config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  resources :users, only: [:show, :edit, :update]
  root to: 'pages#home'
  resources :restaurants do
    resources :reservations
    resources :feedbacks
    # restaurants custom routes
    patch '/update_picture', to: 'restaurants#update_picture', as: :update_picture
    patch '/update_description', to: 'restaurants#update_description', as: :update_description
  end
  # reservations custom routes
  get '/validate', to: "reservations#validate", as: :validate
  post '/validate', to: "reservations#validate_code", as: :validate_code
  get '/codes', to: 'reservations#codes', as: :codes
  get '/error', to: 'reservations#error', as: :error
  post '/users/:id/pref', to: 'users#preferences', as: :user_pref
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-top padded">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <h4>Notre sélection</h4>
          <ul>
            <li>La Tour d'Argent</li>
            <li>Le didon en laisse</li>
            <li>L'Alicheur</li>
            <li>Le Temps des Cerises</li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4">
          <h4>Les quartiers</h4>
          <ul>
            <li>Bastille</li>
            <li>Le Marais</li>
            <li>Champs-Elysées</li>
            <li>La Vilette</li>
            <li>Montmartre</li>
            <li>République</li>
            <li>Quartier Latin</li>
            <li>Trocadéro</li>
            <li>Saint-Germain</li>
            <li>Notre Dame</li>
            <li>Odéon</li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-4">
          <h4>Les cuisines</h4>
          <ul>
            <li>Française</li>
            <li>Chinoise</li>
            <li>Mexicaine</li>
            <li>Italienne</li>
            <li>Japonaise</li>
            <li>Indienne</li>
            <li>Libanaise</li>
          </ul>
        </div>
      </div>
    </div>

  </div>
  <div class="footer-bottom">

  </div>
  <div >
    <ul class="list-inline text-center">
      <li>© La Fine Equipe</li>
    </ul>
    <div style="padding-bottom: 50px;"class="text-center footer-text">
      <i class="fa fa-facebook fa-2x i-f faa-float animated-hover" style="padding: 20px;"></i> <i class="fa fa-twitter fa-2x i-f faa-float animated-hover" style="padding: 20px;"></i> <i class="fa fa-instagram fa-2x i-f faa-float animated-hover" style="padding: 20px;"></i>
    </div>
  </div>
</footer>

app/views/shared/_index_partial.html.erb
<% @restaurants.each do |restaurant| %>
  <div class="col-xs-6">
    <div class="card restaurant_<%= restaurant.id %>">
      <span class="card-bg" style="background-image: url('<%= restaurant.picture.url %>')"></span>
      <span class="card-shadow"></span>
      <span class="card-name"><h2><%= restaurant.name %></h2></span>
      <span class="card-text">
        <p><%= restaurant.borough %></p>
      </span>
      <span class="card-description"><p><%= restaurant.category %></p></span>
      <span class="card-opening"><p >Ouverture prévue le <%= restaurant.opening.day %> <%=month_translator(restaurant.opening.month.to_i) %> </p></span>
      <span class="card-search"><i class="fa fa-search fa-5x text-center"></i></span>
      <%= link_to " ", restaurant_path(restaurant), class: "card-link" %>
      <%= image_tag "logo.png", class: "card-logo_foodkick" %>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon-fixed">
  <div class="container navbar-wagon-container">

    <a href="/">
      <%= image_tag "logo.png", height: '60', width: '70' %>
    </a>
    <a href="/"><span class="navbar-title"><span class="food">FOOD</span><span class="kick">KICK</span></span></a>

    <form action="" class="navbar-wagon-search">
      <!-- <input type="text" class="navbar-wagon-search-input" placeholder="Search for featured stuff">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button> -->
    </form>
    <!-- <hr> -->
    <% unless user_signed_in? && current_user.owner %>
      <%= link_to "Découvrir", restaurants_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <hr>
    <% end %>
    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", style: "margin-top: -18px;", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% if current_user.owner %>
              <li>
                <%= link_to restaurant_path(current_user.restaurant_id) do %>
                  <i class="fa fa-cutlery"></i> <%= t ".profile", default: "Mon Restaurant" %>
                <% end %>
              </li>
              <li>
                <%= link_to restaurant_reservations_path(Restaurant.find(current_user.restaurant_id)) do %>
                  <i class="fa fa-book"></i> <%= t ".profile", default: "Dashboard" %>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to user_path(current_user) do %>
                  <i class="fa fa-user"></i> <%= t ".profile", default: "Profil" %>
                <% end %>
              </li>

            <% end %>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
        <%= link_to t(".sign_in", default: "SE CONNECTER"), new_user_session_path, class: "btn btn-success btn-login" %>
    <% end %>
    <!-- <hr>
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>
</nav>

app/views/shared/_pluralization.html.erb
<%="s" if element > 1 %>

app/views/shared/_search.html.erb
<%= form_tag :controller => 'restaurants', :action => 'search', :method => 'get' do %>
  <%= text_field_tag :search, params[:search], :id => 'search_field' %>
  <%= submit_tag "Search", :name => nil %>
  <%= link_to_function "Clear", "$('search_field').clear()" %>
<% end %>

app/views/shared/_search_results.html.erb
<ul>
  <% @restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.title, :action => 'show', :id => restaurant.id  %></li>
  <% end %>
</ul>