config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  resources :users, only: [:show, :edit, :update]
  root to: 'pages#home'
  resources :restaurants do
    resources :reservations
    resources :feedbacks
    # restaurants custom routes
    patch '/update_picture', to: 'restaurants#update_picture', as: :update_picture
    patch '/update_description', to: 'restaurants#update_description', as: :update_description
  end
  # reservations custom routes
  get '/validate', to: "reservations#validate", as: :validate
  post '/validate', to: "reservations#validate_code", as: :validate_code
  get '/codes', to: 'reservations#codes', as: :codes
  get '/error', to: 'reservations#error', as: :error
  post '/users/:id/pref', to: 'users#preferences', as: :user_pref
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  validates :user_id, presence: true
  validates :restaurant_id, presence: true
  validates :user_id, uniqueness: { scope: :restaurant_id, message: "Attention, tu n'as droit qu'à un voucher par Restaurant"}
end

app/controllers/reservations_controller.rb
require 'securerandom'

class ReservationsController < ApplicationController
  before_action :find_restaurant, only: [:new, :create, :validate_code, :index]
  before_action :find_codes
  before_action :validate_params, only: [:validate_code]
  before_action :average, only: [:index]

  def index
    # @reservations = policy_scope(Reservation)
    @reservations = Reservation.where(restaurant_id: params[:restaurant_id])

    @number_of_views = @restaurant.views
    @number_of_reservations = @reservations.count
    @number_of_validated_reservations = @reservations.where(status: true).count
    @number_of_feedbacks = @reservations.where(feedbacked: true).count
  end

  def create
    @reservation = Reservation.new
    @reservation.user = current_user
    @reservation.restaurant = @restaurant
    # Le code n'a pas été utilisé
    @reservation.status = false
    # Le feedback n'a pas été rendu
    @reservation.feedbacked = false
    # La date limite du feedback est de deux semaines
    @reservation.limit = Time.now + (2*7*24*60*60)
    # On génère un code aléatoire à 6 caractères, chiffres ou lettres
    @code = SecureRandom.hex(3).upcase
    # On regarde si le code n'existe pas déjà
    unless Reservation.exists?(code: @code)
      # On enregistre le code de réservation
      @reservation.code = @code
      # On empêche l'user d'avoir plusieurs réservations en même temps
      # current_user.can_book = false
      if @reservation.save
        redirect_to user_path(current_user)
      else
        redirect_to restaurant_path(@restaurant)
      end
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to codes_path
  end

  def validate
  end

  def validate_code
    if Reservation.exists?(code: params[:code])
      @reservation = Reservation.where(code: params[:code])
      if @reservation.first.restaurant.id == current_user.restaurant_id
        if @reservation.first.status == false
          @reservation = Reservation.where(code: params[:code])
          @reservation.first.status = true
          @reservation.first.save
          redirect_to restaurant_reservations_path(@restaurant.id), notice: "Le code a bien été validé"
        else
          redirect_to restaurant_reservations_path(@restaurant.id), notice: "Oups, le code ne parait pas être valable"
        end
      else
        redirect_to restaurant_reservations_path(@restaurant.id), notice: "Oups, le code ne parait pas être valable"
      end
    else
      redirect_to restaurant_reservations_path(@restaurant.id), notice: "Oups, le code ne parait pas être valable"
    end
  end

  def codes
  end

  private

  def average
    @feedbacks = Feedback.where(:user_id == current_user.id)
    gnlexp = 0
    food = 0
    service = 0
    qualityprice = 0
    vibes = 0
    n = 1
    if  @feedbacks != []
      n = @feedbacks.count.to_f
      @feedbacks.each do |feedback|
        feedback.general_exp_rating ? gnlexp += feedback.general_exp_rating : 0
        feedback.food_rating ? food += feedback.food_rating : 0
        feedback.service_rating ? service += feedback.service_rating : 0
        feedback.quality_to_price_rating ? qualityprice += feedback.quality_to_price_rating : 0
        feedback.vibes_rating ? vibes += feedback.vibes_rating : 0
      end
    end
    @average = [gnlexp/n, food/n, service/n, qualityprice/n, vibes/n]
  end

  def validate_params
    params.permit(:restaurant_id, :code)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def find_codes
    @my_codes = Reservation.where(user_id: current_user.id)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/codes.html.erb
<div class="container">
  <br><br>
  <%if @my_codes == [] %>
    <p class="text-center">Tu n'as pas encore de code de réduction ! Mais rien n'est perdu, viens découvrir nos restos, les plus neufs, les plus beaux et les meilleurs de Paris : </p>
     <br><br>
    <%=link_to restaurants_path do %>
      <div class="text-center">
        <i class="fa fa-cutlery enorme"></i>
      </div>
    <% end %>
  <% else %>
    <ul class= "list-unstyled" style="margin-top: 80px">
      <% @my_codes.each do |code| %>
        <li>
          <strong><%= code.restaurant.name %></strong> - <%= code.code %> - <%= code.status ? "Utilisé" : "Pas utilisé" %> -
            <% unless code.status %>
              Date de validité : <%= code.limit %>
            <% end %>
            <% if code.feedbacked == false && code.status == true %>
              <%= link_to "Donner son feedback", new_restaurant_feedback_path(code.restaurant) %>
            <% end %>
            <%= "Merci pour le feedback" if code.feedbacked %> - <%= link_to "Annuler le code", restaurant_reservation_path(code.restaurant, code), method: 'delete'%>
        </li>
      <% end %>
    </ol>
  <% end %>
</div>

app/views/reservations/error.html.erb
<div class="container padded text-center">
  <div class="row">
    <h2> Désolé, le code ne correspond à rien du tout du tout... </h2>
  </div>
  <%=link_to "Ayez de l'espoir, réessayez, l'Internet sera peut être plus clément", validate_code_path %>
</div>

app/views/reservations/index.html.erb
<div class="container padded text-center">
  <div class="row">

    <ul class="nav nav-tabs" data-tabs="tabs">
      <li class="active"><a data-toggle="tab" href="#coupon"><i class="fa fa-money"></i>
        Coupons</a></li>
      <li><a data-toggle="tab" href="#rating"><i class="fa fa-star"></i>
        Rating</a></li>
      <li><a data-toggle="tab" href="#feedback"><i class="fa fa-comment"></i>
        Feedbacks</a></li>
      <li><a data-toggle="tab" href="#analytics"><i class="fa fa-eye"></i>
        Analytics</a></li>
    </ul>
    <br>

    <div class="tab-content">

      <!-- Coupon -->

      <div id="coupon" class="tab-pane active">
        <div class="container">
          <% if @reservations != []%>
            <div class="row">
              <div class="col-xs-12 col-sm-6 col-sm-offset-3">
                <div class="card-coupon form-group">
                  <h2> Valider un coupon </h2>
                  <%= form_tag(validate_code_path, method: "post") do %>
                    <%= hidden_field_tag(:restaurant_id, value = @restaurant.id) %>
                    <%= text_field_tag :code, nil, {class: "form-control", placeholder: "Ex: FE5FFX" }%>
                    <br>
                    <%= submit_tag("Valider", class: "btn btn-success btn-lg") %>
                  <% end %>
                  <br>
                </div>
              </div>
            </div>
          <% end %>
          <div class="row">
            <h2>Coupons émis</h2>
            <% if @reservations.first != nil %>
              <% @reservations.each do |reservation| %>
                <div class="col-xs-12">
                  <% if !reservation.status %>
                    <strong><%= reservation.user.first_name %> <%= reservation.user.last_name %></strong>
                    <br>
                    <%= reservation.code %>
                    <br>
                    <hr>
                  <% else %>
                    <p> Vous n'avez pas de coupon émis </p>
                    <hr>
                  <% end %>
                <% end %>
              </div>
              <%else%>
                <p> Vous n'avez pas de coupon émis </p>
                <hr>
              <% end %>
          </div>
          <div class="row">
            <h2>Coupons validés</h2>
            <% if @reservations.first != nil %>
              <% @reservations.each do |reservation| %>
                <div class="col-xs-12">
                  <% if reservation.status %>
                    <strong><%= reservation.user.first_name %> <%= reservation.user.last_name %></strong>
                    <br>
                    <%= reservation.code %>
                    <br>
                    <hr>
                  <% else %>
                    <p> Vous n'avez pas de coupon validé </p>
                    <hr>
                  <% end %>
                </div>
              <% end %>
            <% else %>
              <p> Vous n'avez pas de coupon validé </p>
              <hr>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Rating -->

      <div id="rating" class="tab-pane">
        <div class="container">
          <% if @feedbacks != [] %>
              <div class="row ">
                <div class="col-xs-12 col-sm-6 col-sm-offset-3">
                  <div class="card-rating">
                    <h2 class=<%= @average[0] > 2.5 ? "analytic-green" : "analytic-red"%>>
                      <%= @average[0] %>
                    </h2>
                    <p> Expérience Générale </p>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-xs-12 col-sm-3">
                  <div class="card-rating">
                    <h4 class=<%= @average[1] > 2.5 ? "analytic-green" : "analytic-red"%>>
                      <%= @average[1] %>
                    </h4>
                    <p> Cuisine </p>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-3">
                  <div class="card-rating">
                    <h4 class=<%= @average[2] > 2.5 ? "analytic-green" : "analytic-red"%>>
                      <%= @average[2] %>
                    </h4>
                    <p> Service </p>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-3">
                  <div class="card-rating">
                    <h4 class=<%= @average[3] > 2.5 ? "analytic-green" : "analytic-red"%>>
                      <%= @average[3] %>
                    </h4>
                    <p> Rapport qualité/prix </p>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-3">
                  <div class="card-rating">
                    <h4 class=<%= @average[4] > 2.5 ? "analytic-green" : "analytic-red"%>>
                      <%= @average[4] %>
                    </h4>
                  <p> Ambiance </p>
                </div>
              </div>
            </div>
          <% else %>
            <br><br><br><br>
            <div class="col-xs-12 col-sm-6 col-sm-offset-3">
              <h2> Vous n'avez pas encore reçu de note ! </h2>
              <hr>
            </div>
          <% end %>
        </div>
      </div>

      <!-- Feedback -->

      <div id="feedback" class="tab-pane">
        <div class="container">
          <div class="row">
            <% if @feedbacks.first != nil %>
              <% @feedbacks.each do |feedback| %>
                <div class="col-xs-12 col-sm-6">
                  <div class="text-center card-rating">
                    <h3><%= User.find(feedback.user_id).first_name %> <%= User.find(feedback.user_id).last_name %></h3>
                    <p class="date"> <%= feedback.created_at.day %>/<%= feedback.created_at.month %>/<%=feedback.created_at.year %></p>
                    <p>
                      <strong>Avez-vous apprécié votre expérience ?</strong><br>
                      <%= feedback.general_exp %>
                    </p>
                    <p>
                      <strong>Qu'avez vous pensé de la cuisine ?</strong><br>
                      <%= feedback.food %>
                    </p>
                    <p>
                      <strong>Qu'avez vous pensé du service ?</strong><br>
                      <%= feedback.service %>
                    </p>
                    <p>
                      <strong>Qu'avez-vous pensé du rapport qualité/prix ?</strong><br>
                      <%= feedback.quality_to_price %>
                    </p>
                    <p>
                      <strong>Avez-vous apprécié l'ambiance du restaurant ?</strong><br>
                      <%= feedback.vibes %>
                    </p>
                  </div>
                </div>
              <% end %>
            <% else %>
              <br><br><br><br>
              <div class="col-xs-12 col-sm-6 col-sm-offset-3">
                <h2> Vous n'avez pas encore reçu de feedback !</h2>
                <hr>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Analytics-->

      <div id="analytics" class="tab-pane">
        <div class="container">
          <div class="row ">
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="card-analytic green">
                <i class="fa fa-eye icon"></i>
                <h2 class="analytic"> <%= @number_of_views %> </h2>
                <p> Vue<%= render 'shared/pluralization', element: @number_of_views %> </p>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="card-analytic green">
                <i class="fa fa-book icon"></i>
                <h2 class="analytic"> <%= @number_of_reservations %> </h2>
                <p>
                  Réservation<%= render 'shared/pluralization', element: @number_of_reservations %>
                </p>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="card-analytic green">
                <i class="fa fa-money icon"></i>
                <h2 class="analytic"> <%= @number_of_validated_reservations %> </h2>
                <p>
                  Réservation<%= render 'shared/pluralization', element: @number_of_validated_reservations %> validée<%= render 'shared/pluralization', element: @number_of_validated_reservations %>
                </p>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
              <div class="card-analytic green">
                <i class="fa fa-comment icon"></i>
                <h2 class="analytic"> <%= @number_of_feedbacks %> </h2>
                <p>
                  Feedback<%= render 'shared/pluralization', element: @number_of_feedbacks %> reçu<%= render 'shared/pluralization', element: @number_of_feedbacks %>
                </p>
              </div>
            </div>
          </div>
<!--           <br><br><br>
          <div>
            <h3>Plus de visibilité ? Passez en sponsorisé !</h3>
            <br><br>
            <form action="" method="POST">
              <script
                src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="pk_test_6pRNASCoBOKtIshFeQd4XMUh"
                data-amount="990"
                data-name="Foodkick"
                data-description="Un mois sponsorisé (9.90€)"
                data-image="https://pbs.twimg.com/profile_images/483691332268208128/bdNi5Gs5.jpeg"
                data-locale="auto">
              </script>
            </form>
          </div> -->
        </div>
      </div>
    </div>
  </div>
</div>