config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  resources :users, only: [:show, :edit, :update]
  root to: 'pages#home'
  resources :restaurants do
    resources :reservations
    resources :feedbacks
    # restaurants custom routes
    patch '/update_picture', to: 'restaurants#update_picture', as: :update_picture
    patch '/update_description', to: 'restaurants#update_description', as: :update_description
  end
  # reservations custom routes
  get '/validate', to: "reservations#validate", as: :validate
  post '/validate', to: "reservations#validate_code", as: :validate_code
  get '/codes', to: 'reservations#codes', as: :codes
  get '/error', to: 'reservations#error', as: :error
  post '/users/:id/pref', to: 'users#preferences', as: :user_pref
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  def self.search(search)
    where("name LIKE ?", "%#{search}%")
    where("borough LIKE ?", "%#{search}%")
  end

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  BOROUGH = ['Marais', 'Montmartre', 'Bastille', 'Saint-Germain']
  has_many :courses
  has_many :reservations
  has_one :schedule
  has_one :user
  validates :name, presence: true
  validates :address, presence: true
  validates :zip_code, presence: true, format: { with: /750((0)[1-9]||((1||2)\d))/}
  validates :borough, presence: true
  validates :category, presence: true
  #validates :email, presence: true, format: { with: /(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])/ }
  validates :price_min, presence: true
  validates :price_max, presence: true

  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :destroy]
  before_action :voucher, only: [:show]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @pref_borough = PrefBorough.uniq
    @pref_cat = PrefCat.uniq
    if params[:ar_id]
      @restaurants = policy_scope(Restaurant.where(zip_code: params[:ar_id]))
    elsif params[:pref_quartier]
      @restaurants = policy_scope(Restaurant.where(borough_label: params[:pref_quartier]))
    elsif params[:pref_cat]
      @restaurants = policy_scope(Restaurant.where(cat_label: params[:pref_cat]))
    else
      @restaurants = policy_scope(Restaurant.all)
    end
    @markers = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      #marker.picture(url: view_context.image_path('toc.png'), width: 35, height: 70 )
    end

    @markers.select! { |hash| hash[:lat] != nil && hash[:lng] != nil }
  end

  def show
    authorize @restaurant
    if user_signed_in?
      if current_user.restaurant_id != @restaurant.id
        @restaurant.views += 1
        @restaurant.save
      end
    else
      @restaurant.views += 1
      @restaurant.save
    end
    @reservation = Reservation.new
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
  end

  def edit
  end

  def update_picture
    set_restaurant(:restaurant_id)
    if @restaurant.update(edit_params(:seed_picture))
      redirect_to restaurant_path(@restaurant), notice: 'Votre image a été changé avec succès'
    else
      redirect_to restaurant_path(@restaurant), notice: "Oups ! Ca n'a pas marché"
    end
  end

  def update_description
    set_restaurant(:restaurant_id)
    if @restaurant.update(edit_params(:description))
      redirect_to restaurant_path(@restaurant), notice: 'Votre description a été changée avec succès'
    else
      redirect_to restaurant_path(@restaurant), notice: "Oups ! Ca n'a pas marché"
    end
  end

  private

  def edit_params(param)
    params.require(:restaurant).permit(:restaurant_id, param)
  end

  def set_restaurant(id = :id)
    @restaurant = Restaurant.find(params[id])
  end

  def voucher
    if user_signed_in?
      @booked = true if Reservation.where(user_id: current_user.id, restaurant_id: params[:id]) != []
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def index_home_category(italian, french, viet, thai, japanese, bastille, notre_dame, marais, villette, abbesses)
    cat_coll = [italian, french, viet, thai, japanese]
    borough_coll = [bastille, notre_dame, marais, villette, abbesses]

    result = Restaurants.where(category: collection )


  end

  def month_translator(month)
  return "Janvier" if month == 1
  return "Février" if month == 2
  return "Mars" if month == 3
  return "Avril" if month == 4
  return "Mai" if month == 5
  return "Juin" if month == 6
  return "Juillet" if month == 7
  return "Août" if month == 8
  return "Septembre" if month == 9
  return "Octobre" if month == 10
  return "Novembre" if month == 11
  return "Décembre" if month == 12
end
end

app/views/restaurants/_coupon_form.html.erb
<%= simple_form_for [@restaurant, @reservation] do |f| %>
  <%= f.button :submit, "Obtenir mon coupon", class: "btn btn-success btn-lg", style: "background-color: #ff1654; border: none;" %>
<% end %>

app/views/restaurants/index.html.erb
<% @no_footer = false %>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-7">
      <div class="row">


        <span id="quartier">
          <div class="dropdown" id="divdrop">
            <button class=" btn-default dropdown-toggle btn-homepage" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Quartiers</button>
            <ul class="dropdown-menu col-sm-6" aria-labelledby="dropdownMenu1">
              <li><%= link_to "Le Marais", restaurants_path(pref_quartier: "marais")%></li>
              <li><%= link_to "Abbesses", restaurants_path(pref_quartier: "abbesses")%></li>
              <li><%= link_to "Quartier Latin", restaurants_path(pref_quartier: "quartierlatin")%></li>
              <li><%= link_to "Montmartre", restaurants_path(pref_quartier: "montmartre")%></li>
              <li><%= link_to "Champs Elysées", restaurants_path(pref_quartier: "champs")%></li>
              <li><%= link_to "Notre Dame", restaurants_path(pref_quartier: "notredame")%></li>
              <li><%= link_to "Villette", restaurants_path(pref_quartier: "villette")%></li>
            </ul>

        </div>
        </span>


        <div class="dropdown right" id="divdrop">
            <button class=" btn-default dropdown-toggle btn-homepage" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Horizons</button>
            <ul class="dropdown-menu bis" aria-labelledby="dropdownMenu2">
              <li><%= link_to "Cuisine Française", restaurants_path(pref_cat: "francais")%></li>
              <li><%= link_to "Italien", restaurants_path(pref_cat: "italien")%></li>
              <li><%= link_to "Japonais", restaurants_path(pref_cat: "japonais")%></li>
              <li><%= link_to "Vietnamien", restaurants_path(pref_cat: "viet")%></li>
              <li><%= link_to "Original", restaurants_path(pref_cat: "original")%></li>
              <li><%= link_to "Burger", restaurants_path(pref_cat: "burger")%></li>
              <li><%= link_to "Argentin", restaurants_path(pref_cat: "argentin")%></li>

            </ul>
        </div>
        <br>


        <%= render 'shared/index_partial' %>

      </div>
      <div class="row" style="padding-left: 50px; padding-right: 50px; ">
        <hr>
        <p style="padding-bottom: 20px;">Vous pouvez également découvrir <%= link_to "Le Marais" %> · <%= link_to "Bastille" %> · <%= link_to "Abbesses" %></p>
      </div>
    </div>
    <div class="col-xs-5 search-map">
      <div id="map" style="width: 100%; height: 100vh;"></div>
      <% content_for(:after_js) do %>
        <%= javascript_tag do %>
          $(document).on('ready', function() {
            handler = Gmaps.build('Google');
            handler.buildMap({

            <!-- RAJOUTE le style de la carte dans le builder -->
            provider: {
            styles: [
    {
        "featureType": "landscape",
        "stylers": [
            {
                "hue": "#FFBB00"
            },
            {
                "saturation": 43.400000000000006
            },
            {
                "lightness": 37.599999999999994
            },
            {
                "gamma": 1
            },

            {
                "z-index": 0
            }


        ]
    },
    {
        "featureType": "road.highway",
        "stylers": [
            {
                "hue": "#FFC200"
            },
            {
                "saturation": -61.8
            },
            {
                "lightness": 45.599999999999994
            },
            {
                "gamma": 1
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "stylers": [
            {
                "hue": "#FF0300"
            },
            {
                "saturation": -100
            },
            {
                "lightness": 51.19999999999999
            },
            {
                "gamma": 1
            }
        ]
    },
    {
        "featureType": "road.local",
        "stylers": [
            {
                "hue": "#FF0300"
            },
            {
                "saturation": -100
            },
            {
                "lightness": 52
            },
            {
                "gamma": 1
            }
        ]
    },
    {
        "featureType": "water",
        "stylers": [
            {
                "hue": "#0078FF"
            },
            {
                "saturation": -13.200000000000003
            },
            {
                "lightness": 2.4000000000000057
            },
            {
                "gamma": 1
            }
        ]
    },
    {
        "featureType": "poi",
        "stylers": [
            {
                "hue": "#00FF6A"
            },
            {
                "saturation": -1.0989010989011234
            },
            {
                "lightness": 11.200000000000017
            },
            {
                "gamma": 1
            }
        ]
    }
]
          },
          <!-- Fin du style de la carte -->
            internal: { id: 'map' } }, function(){
              markers = handler.addMarkers(<%= raw @markers.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
            });
          })
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<% @footer = true %>
<header>

  <div class="banner text-center" style="background-image: url('<%= @restaurant.picture.url %>')">
    <div class="banner-shadow"></div>
    <div class="banner-content">
      <div class="restaurant-category">
        <p><%=@restaurant.category%></p>
      </div>
      <div class="restaurant-opening">
        <p>Ouverture : <%=@restaurant.opening%></p>
      </div>
      <h1><%= @restaurant.name %></h1>
      <p><%= @restaurant.description[0..70]%>...</p>
        <% if user_signed_in? %>

          <% if current_user.owner == false || current_user.owner == nil  %>

            <% if @booked %>
              <%=link_to 'Voir mon code', user_path(coming_from_reservation: 1) %>
            <% else %>
              <%= render 'coupon_form' %>
              <div class="restaurant-discount">
                <p><%= (@restaurant.discount*100).to_i %>%</p>
              </div>
              <% end %>
          <% elsif current_user.restaurant_id == @restaurant.id %>
            <%= simple_form_for @restaurant, url: restaurant_update_picture_path(@restaurant), method: :patch do |f| %>
              <!-- <%= f.input :seed_picture %> -->
              <%= f.button :submit, class: "btn btn-primary", value: "Editer mon profil"%>
            <% end %>
          <% end %>
        <% else %>
          <%= render 'coupon_form' %>
          <div class="restaurant-discount">
            <p><%= -(@restaurant.discount*100).to_i %>%</p>
          </div>
        <% end %>
    </div>
  </div>
</header>

<div class="restaurant-show-content">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8">
         <br>
         <img src="https://images.unsplash.com/photo-1414358154612-ae3d3c120004?q=80&fm=jpg&s=988c3ac3e8fc7e48d5d7f6d9bd325c6a" class="img-thumbnail" alt="Cinque Terre">
      </div>
      <div class="col-xs-12 col-md-4">
        <h3>UN VOYAGE</h3>
        <p style="text-align: justify">
          D'origine chinoise, le chef Guillaume Chen te propose de goûter à une cuisine familiale saine et douce. Beijing 8 est né du constat de Guillaume que beaucoup des petits restaurants chinois de quartier offrent "une cuisine standardisée, sans saveur ni profondeur qui ne reflètent ni la diversité, ni l'authenticité de la cuisine chinoise". De ce constat est né un rêve et de ce rêve est né Beijing 8.
        </p>
        <br>
        <p style="text-align: justify">
          Guillaume a passé des mois à apprendre et réapprendre la cuisine de sa grand-mère, celle qui a éveillé ses papilles et qui l'a pris sous son aile. Il a refondé sa cuisine pour offrir des plats faits maisons traditionnels et délicieux. Sa femme Sandrine accueille les hotes chaleureusement et offre un service sans faute.
        </p>
        <% if user_signed_in? %>
          <% if current_user.owner && current_user.restaurant_id == @restaurant.id %>
            <%= simple_form_for @restaurant, url: restaurant_update_description_path(@restaurant), method: :patch do |f| %>
              <%= f.input :description %>
              <%= f.button :submit, class: "btn btn-primary", value: "Modifier la description" %>
            <% end %>
          <% end -%>
        <% end %>
      </div>
    </div>
    <br>
    <div class="container padded menu">
      <div class="row sm-padded">
        <h3 class="text-center">ENTREES</h3>
          <br>
          <% @restaurant.courses.where(category: "Entrée").each do |entree| %>
            <div class="col-xs-12 col-md-4">
              <span class="pull-left"><strong><%=entree.name%></strong></span>
              <span class="pull-right"><%=entree.price %>€</span>
              <div style="clear:both"></div>
              <p class="description"><%=entree.description%></p>
            </div>
          <% end %>
      </div>
      <div class="row sm-padded">
        <h3 class="text-center">PLATS</h3>
          <br>
          <% @restaurant.courses.where(category: "Plat").each do |plat| %>
            <div class="col-xs-12 col-md-4">
              <span class="pull-left"><strong><%=plat.name%></strong></span>
              <span class="pull-right"><%=plat.price %>€</span>
              <div style="clear:both"></div>
              <p class="description"><%=plat.description%></p>
            </div>
          <% end %>
      </div>
      <div class="row">
        <h3 class="text-center">DESSERT</h3>
          <br>
          <% @restaurant.courses.where(category: "Dessert").each do |dessert| %>
            <div class="col-xs-12 col-md-4">
              <span class="pull-left"><strong><%=dessert.name%></strong></span>
              <span class="pull-right"><%=dessert.price %>€</span>
              <div style="clear:both"></div>
              <p class="description"><%=dessert.description%></p>
            </div>
          <% end %>
      </div>
    </div>

    <br>


    <div class="row">
      <div class="col-xs-12 col-md-4">
        <%= image_tag 'https://unsplash.com/photos/MtqG1lWcUw0/download', class: "img-thumbnail"%>
      </div>
      <div class="col-xs-12 col-md-4">
        <%= image_tag "https://unsplash.com/photos/ca9NRoZcSPA/download", class: "img-thumbnail"%>
      </div>
      <div class="col-xs-12 col-md-4">
        <%= image_tag "https://unsplash.com/photos/TULqBUELe9c/download", class: "img-thumbnail"%>
      </div>
    </div>
    <div class="row padded">
      <div class="col-xs-12 col-md-4 text-justify">
        <h2>Guillaume Chen</h2>
        <h4>Le Chef</h4>
        <p style="text-align: justify">
          Guillaume cuisine tous ses plats avec l'amour qu'y mettait sa grand-mère. Il traduit l'essence de la cuisine chinoise dans votre assiette pour le bonheur de vos papilles.
        </p>
      </div>
      <div class="col-xs-12 col-md-4 text-justify">
        <h2>Sandrine Chen</h2>
        <h4>La Patronne</h4>
        <p style="text-align: justify">
          Sans elle, Beijing 8 ne tournerait pas rond, elle donne tout, tous les jours pour la réussite du restaurant, la satisfaction de ses clients et le bonheur de Marcel.
        </p>
      </div>
      <div class="col-xs-12 col-md-4 text-justify">
        <h2>Marcel</h2>
        <h4>Le garde</h4>
        <p style="text-align: justify">
          Marcel est peut être le plus chaleureux de tous les gardes, il vous accueillera les pattes ouvertes et sait se faire oublier pendant le repas. Mais attention aux méchants !
        </p>
      </div>
    </div>
  </div>
</div>

<div class="text-center">
  <% if user_signed_in? %>
    <% if current_user.owner == false || current_user.owner == nil %>
      <% if @booked %>
        <%=link_to 'Voir mon code', user_path(coming_from_reservation: 1) %>
      <% else %>
        <%= render 'coupon_form' %>
      <% end %>
    <% end %>
  <% else %>
    <%= render 'coupon_form' %>
  <% end %>
</div>
<br><br><br><br>